# Generated by Django 5.0.3 on 2024-03-18 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tsg_website", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="formatted_price",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="car",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="media"),
        ),
    ]
