# Generated by Django 5.0.3 on 2024-03-18 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tsg_website", "0003_rename_photo_car_photo1_car_photo2_car_photo3_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="car",
            name="photo1",
        ),
        migrations.RemoveField(
            model_name="car",
            name="photo2",
        ),
        migrations.RemoveField(
            model_name="car",
            name="photo3",
        ),
        migrations.RemoveField(
            model_name="car",
            name="photo4",
        ),
        migrations.RemoveField(
            model_name="car",
            name="photo5",
        ),
        migrations.CreateModel(
            name="Photo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="media")),
                (
                    "car",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="tsg_website.car",
                    ),
                ),
            ],
        ),
    ]
