# Generated by Django 4.0.6 on 2024-03-18 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsg_website', '0004_remove_car_photo1_remove_car_photo2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='is_sold',
            field=models.BooleanField(default=False),
        ),
    ]
