# Generated by Django 5.0.3 on 2024-03-22 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsg_website', '0006_car_body_color_car_body_type_car_fuel_type_car_make_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='make',
            field=models.CharField(blank=True, max_length=100, verbose_name='Make'),
        ),
    ]
