# Generated by Django 5.0.3 on 2024-03-23 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tsg_website', '0008_gallery'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Gallery',
        ),
    ]
