# Generated by Django 5.0.3 on 2024-03-23 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsg_website', '0010_gallery_galleryphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryphoto',
            name='gallery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_photos', to='tsg_website.gallery'),
        ),
        migrations.AlterField(
            model_name='galleryphoto',
            name='image',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
