# Generated by Django 5.0.3 on 2024-03-28 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsg_website', '0011_alter_galleryphoto_gallery_alter_galleryphoto_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
